# Generated by Django 3.0.6 on 2020-05-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200514_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='anno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
