# Generated by Django 3.0.6 on 2020-05-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200517_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='anno',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
