# Generated by Django 3.0.6 on 2020-05-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_item_data_inserzione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='data_inserzione',
            field=models.DateField(),
        ),
    ]
