# Generated by Django 3.0.6 on 2020-06-09 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_itemimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='camper',
            new_name='all_items',
        ),
    ]
