# Generated by Django 3.0.6 on 2020-06-11 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20200609_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemimage',
            name='all_items',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.Item'),
        ),
    ]
